GENFIT: genfit::HMatrixUV Class Reference
genfit::HMatrixUV Class Reference
AbsHMatrix implementation for two-dimensional MeasurementOnPlane and RKTrackRep parameterization.
#include <HMatrixUV.h>
Public Member Functions
HMatrixUV ()
const TMatrixD & getMatrix () const
Get the actual matrix representation.
TVectorD Hv (const TVectorD &v) const
H*v.
TMatrixD MHt (const TMatrixDSym &M) const
M*H^t.
TMatrixD MHt (const TMatrixD &M) const
void HMHt (TMatrixDSym &M) const
similarity: H*M*H^t
virtual HMatrixUV * clone () const
virtual bool isEqual (const AbsHMatrix &other) const
virtual void Print (const Option_t *="") const
Public Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix ()
virtual ~AbsHMatrix ()
bool operator== (const AbsHMatrix &other) const
bool operator!= (const AbsHMatrix &other) const
Additional Inherited Members
Protected Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix (const AbsHMatrix &o)
AbsHMatrix & operator= (const AbsHMatrix &)
Detailed Description
AbsHMatrix implementation for two-dimensional MeasurementOnPlane and RKTrackRep parameterization.
This projects out u and v. H = (0, 0, 0, 1, 0) (0, 0, 0, 0, 1)
Definition at line 39 of file HMatrixUV.h.
Constructor & Destructor Documentation
HMatrixUV()
genfit::HMatrixUV::HMatrixUV () inline
Definition at line 44 of file HMatrixUV.h.
Referenced by clone().
Member Function Documentation
clone()
virtual HMatrixUV* genfit::HMatrixUV::clone () const inline virtual
Implements genfit::AbsHMatrix.
Definition at line 55 of file HMatrixUV.h.
References HMatrixUV().
getMatrix()
const TMatrixD & genfit::HMatrixUV::getMatrix () const virtual
Get the actual matrix representation.
Implements genfit::AbsHMatrix.
Definition at line 33 of file HMatrixUV.cc.
Referenced by genfit::GblFitterInfo::reset().
HMHt()
void genfit::HMatrixUV::HMHt (TMatrixDSym & M) const virtual
similarity: H*M*H^t
Reimplemented from genfit::AbsHMatrix.
Definition at line 86 of file HMatrixUV.cc.
Hv()
TVectorD genfit::HMatrixUV::Hv (const TVectorD & v) const virtual
H*v.
Reimplemented from genfit::AbsHMatrix.
Definition at line 43 of file HMatrixUV.cc.
isEqual()
virtual bool genfit::HMatrixUV::isEqual (const AbsHMatrix & other) const inline virtual
Implements genfit::AbsHMatrix.
Definition at line 57 of file HMatrixUV.h.
MHt() [1/2]
TMatrixD genfit::HMatrixUV::MHt (const TMatrixDSym & M) const virtual
M*H^t.
Reimplemented from genfit::AbsHMatrix.
Definition at line 56 of file HMatrixUV.cc.
MHt() [2/2]
TMatrixD genfit::HMatrixUV::MHt (const TMatrixD & M) const virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 71 of file HMatrixUV.cc.
Print()
void genfit::HMatrixUV::Print (const Option_t * = "") const virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 105 of file HMatrixUV.cc.
References genfit::printOut.
The documentation for this class was generated from the following files:
/home/eicuser/GenFit/measurements/include/HMatrixUV.h
/home/eicuser/GenFit/measurements/src/HMatrixUV.cc