GENFIT: genfit::HMatrixU Class Reference
genfit::HMatrixU Class Reference
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
#include <HMatrixU.h>
Public Member Functions
HMatrixU ()
const TMatrixD & getMatrix () const
Get the actual matrix representation.
TVectorD Hv (const TVectorD &v) const
H*v.
TMatrixD MHt (const TMatrixDSym &M) const
M*H^t.
TMatrixD MHt (const TMatrixD &M) const
void HMHt (TMatrixDSym &M) const
similarity: H*M*H^t
virtual HMatrixU * clone () const
virtual bool isEqual (const AbsHMatrix &other) const
virtual void Print (const Option_t *="") const
Public Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix ()
virtual ~AbsHMatrix ()
bool operator== (const AbsHMatrix &other) const
bool operator!= (const AbsHMatrix &other) const
Additional Inherited Members
Protected Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix (const AbsHMatrix &o)
AbsHMatrix & operator= (const AbsHMatrix &)
Detailed Description
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
This projects out u. H = (0, 0, 0, 1, 0)
Definition at line 37 of file HMatrixU.h.
Constructor & Destructor Documentation
HMatrixU()
genfit::HMatrixU::HMatrixU () inline
Definition at line 41 of file HMatrixU.h.
Referenced by clone().
Member Function Documentation
clone()
virtual HMatrixU* genfit::HMatrixU::clone () const inline virtual
Implements genfit::AbsHMatrix.
Definition at line 52 of file HMatrixU.h.
References HMatrixU().
getMatrix()
const TMatrixD & genfit::HMatrixU::getMatrix () const virtual
Get the actual matrix representation.
Implements genfit::AbsHMatrix.
Definition at line 33 of file HMatrixU.cc.
Referenced by genfit::GblFitterInfo::constructGblPoint().
HMHt()
void genfit::HMatrixU::HMHt (TMatrixDSym & M) const virtual
similarity: H*M*H^t
Reimplemented from genfit::AbsHMatrix.
Definition at line 81 of file HMatrixU.cc.
Hv()
TVectorD genfit::HMatrixU::Hv (const TVectorD & v) const virtual
H*v.
Reimplemented from genfit::AbsHMatrix.
Definition at line 42 of file HMatrixU.cc.
isEqual()
virtual bool genfit::HMatrixU::isEqual (const AbsHMatrix & other) const inline virtual
Implements genfit::AbsHMatrix.
Definition at line 54 of file HMatrixU.h.
MHt() [1/2]
TMatrixD genfit::HMatrixU::MHt (const TMatrixDSym & M) const virtual
M*H^t.
Reimplemented from genfit::AbsHMatrix.
Definition at line 53 of file HMatrixU.cc.
MHt() [2/2]
TMatrixD genfit::HMatrixU::MHt (const TMatrixD & M) const virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 67 of file HMatrixU.cc.
Print()
void genfit::HMatrixU::Print (const Option_t * = "") const virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 90 of file HMatrixU.cc.
References genfit::printOut.
The documentation for this class was generated from the following files:
/home/eicuser/GenFit/measurements/include/HMatrixU.h
/home/eicuser/GenFit/measurements/src/HMatrixU.cc