GENFIT: genfit::HMatrixPhi Class Reference
genfit::HMatrixPhi Class Reference
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
#include <HMatrixPhi.h>
Public Member Functions
HMatrixPhi (double phi=0)
const TMatrixD & getMatrix () const
Get the actual matrix representation.
TVectorD Hv (const TVectorD &v) const
H*v.
TMatrixD MHt (const TMatrixDSym &M) const
M*H^t.
TMatrixD MHt (const TMatrixD &M) const
void HMHt (TMatrixDSym &M) const
similarity: H*M*H^t
virtual HMatrixPhi * clone () const
virtual bool isEqual (const AbsHMatrix &other) const
virtual void Print (const Option_t *="") const
Public Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix ()
virtual ~AbsHMatrix ()
bool operator== (const AbsHMatrix &other) const
bool operator!= (const AbsHMatrix &other) const
Public Attributes
ClassDef(HMatrixPhi, 1) private double cosPhi_
double sinPhi_
Additional Inherited Members
Protected Member Functions inherited from genfit::AbsHMatrix
AbsHMatrix (const AbsHMatrix &o)
AbsHMatrix & operator= (const AbsHMatrix &)
Detailed Description
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
For one dimensional measurements which are rotated by phi against U of the DetPlane H = (0, 0, 0, cos(phi), sin(phi))
Definition at line 37 of file HMatrixPhi.h.
Constructor & Destructor Documentation
HMatrixPhi()
genfit::HMatrixPhi::HMatrixPhi (double phi = 0)
Definition at line 37 of file HMatrixPhi.cc.
Referenced by clone().
Member Function Documentation
clone()
virtual HMatrixPhi* genfit::HMatrixPhi::clone () const inline virtual
Implements genfit::AbsHMatrix.
Definition at line 52 of file HMatrixPhi.h.
References HMatrixPhi().
getMatrix()
const TMatrixD & genfit::HMatrixPhi::getMatrix () const virtual
Get the actual matrix representation.
Implements genfit::AbsHMatrix.
Definition at line 45 of file HMatrixPhi.cc.
References cosPhi_, and sinPhi_.
HMHt()
void genfit::HMatrixPhi::HMHt (TMatrixDSym & M) const virtual
similarity: H*M*H^t
Reimplemented from genfit::AbsHMatrix.
Definition at line 93 of file HMatrixPhi.cc.
References cosPhi_, and sinPhi_.
Hv()
TVectorD genfit::HMatrixPhi::Hv (const TVectorD & v) const virtual
H*v.
Reimplemented from genfit::AbsHMatrix.
Definition at line 54 of file HMatrixPhi.cc.
References cosPhi_, and sinPhi_.
isEqual()
bool genfit::HMatrixPhi::isEqual (const AbsHMatrix & other) const virtual
Implements genfit::AbsHMatrix.
Definition at line 103 of file HMatrixPhi.cc.
MHt() [1/2]
TMatrixD genfit::HMatrixPhi::MHt (const TMatrixDSym & M) const virtual
M*H^t.
Reimplemented from genfit::AbsHMatrix.
Definition at line 65 of file HMatrixPhi.cc.
References cosPhi_, and sinPhi_.
MHt() [2/2]
TMatrixD genfit::HMatrixPhi::MHt (const TMatrixD & M) const virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 79 of file HMatrixPhi.cc.
References cosPhi_, and sinPhi_.
Print()
void genfit::HMatrixPhi::Print (const Option_t * = "") const virtual
Reimplemented from genfit::AbsHMatrix.
Definition at line 110 of file HMatrixPhi.cc.
References genfit::printOut.
Member Data Documentation
cosPhi_
ClassDef (HMatrixPhi,1) private double genfit::HMatrixPhi::cosPhi_
Definition at line 58 of file HMatrixPhi.h.
Referenced by getMatrix(), HMHt(), Hv(), and MHt().
sinPhi_
double genfit::HMatrixPhi::sinPhi_
Definition at line 64 of file HMatrixPhi.h.
Referenced by getMatrix(), HMHt(), Hv(), and MHt().
The documentation for this class was generated from the following files:
/home/eicuser/GenFit/measurements/include/HMatrixPhi.h
/home/eicuser/GenFit/measurements/src/HMatrixPhi.cc