GENFIT: genfit::PlanarMeasurement Class Reference
genfit::PlanarMeasurement Class Reference
Measurement class implementing a planar hit geometry (1 or 2D).
#include <PlanarMeasurement.h>
Public Member Functions
PlanarMeasurement (int nDim=1)
PlanarMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint)
virtual ~PlanarMeasurement ()
virtual AbsMeasurement * clone () const
Deep copy ctor for polymorphic class.
int getPlaneId () const
virtual SharedPlanePtr constructPlane (const StateOnPlane &state) const
virtual std::vector< MeasurementOnPlane * > constructMeasurementsOnPlane (const StateOnPlane &state) const
virtual const AbsHMatrix * constructHMatrix (const AbsTrackRep *) const
virtual void setPlane (const SharedPlanePtr &physicalPlane, int planeId=-1)
void setStripV (bool v=true)
Use if the coordinate for 1D hits measured in V direction.
Public Member Functions inherited from genfit::AbsMeasurement
AbsMeasurement ()
AbsMeasurement (int nDims)
AbsMeasurement (const TVectorD &rawHitCoords, const TMatrixDSym &rawHitCov, int detId, int hitId, TrackPoint *trackPoint)
virtual ~AbsMeasurement ()
TrackPoint * getTrackPoint () const
void setTrackPoint (TrackPoint *tp)
const TVectorD & getRawHitCoords () const
const TMatrixDSym & getRawHitCov () const
TVectorD & getRawHitCoords ()
TMatrixDSym & getRawHitCov ()
int getDetId () const
int getHitId () const
virtual bool isLeftRightMeasurement () const
If the AbsMeasurement is a wire hit, the left/right resolution will be used.
virtual int getLeftRightResolution () const
unsigned int getDim () const
void setRawHitCoords (const TVectorD &coords)
void setRawHitCov (const TMatrixDSym &cov)
void setDetId (int detId)
void setHitId (int hitId)
virtual void Print (const Option_t *="") const
Protected Attributes
SharedPlanePtr physicalPlane_
int planeId_
This is persistent, but '!' makes ROOT shut up.
bool stripV_
Protected Attributes inherited from genfit::AbsMeasurement
TVectorD rawHitCoords_
TMatrixDSym rawHitCov_
int detId_
int hitId_
TrackPoint * trackPoint_
Pointer to TrackPoint where the measurement belongs to.
Additional Inherited Members
Protected Member Functions inherited from genfit::AbsMeasurement
AbsMeasurement (const AbsMeasurement &)
protect from calling copy c'tor from outside the class. Use clone() if you want a copy!
Detailed Description
Measurement class implementing a planar hit geometry (1 or 2D).
Author
Christian Höppner (Technische Universität München, original author)
Sebastian Neubert (Technische Universität München, original author)
Johannes Rauch (Technische Universität München, original author)
The main feature of this type of hit is, that the detector plane is defined by the detector hardware.
Definition at line 44 of file PlanarMeasurement.h.
Constructor & Destructor Documentation
PlanarMeasurement() [1/2]
genfit::PlanarMeasurement::PlanarMeasurement (int nDim = 1)
Definition at line 33 of file PlanarMeasurement.cc.
Referenced by clone().
PlanarMeasurement() [2/2]
genfit::PlanarMeasurement::PlanarMeasurement (const TVectorD & rawHitCoords, const TMatrixDSym & rawHitCov, int detId, int hitId, TrackPoint * trackPoint)
Definition at line 39 of file PlanarMeasurement.cc.
References genfit::AbsMeasurement::rawHitCoords_.
~PlanarMeasurement()
virtual genfit::PlanarMeasurement::~PlanarMeasurement () inline virtual
Definition at line 50 of file PlanarMeasurement.h.
Member Function Documentation
clone()
virtual AbsMeasurement* genfit::PlanarMeasurement::clone () const inline virtual
Deep copy ctor for polymorphic class.
Implements genfit::AbsMeasurement.
Definition at line 52 of file PlanarMeasurement.h.
References PlanarMeasurement().
constructHMatrix()
const AbsHMatrix * genfit::PlanarMeasurement::constructHMatrix (const AbsTrackRep *) const virtual
Returns a new AbsHMatrix object. Caller must take ownership.
Implements genfit::AbsMeasurement.
Definition at line 67 of file PlanarMeasurement.cc.
References genfit::AbsMeasurement::rawHitCoords_, and stripV_.
Referenced by constructMeasurementsOnPlane().
constructMeasurementsOnPlane()
std::vector< MeasurementOnPlane * > genfit::PlanarMeasurement::constructMeasurementsOnPlane (const StateOnPlane & state) const virtual
Construct MeasurementOnPlane on plane of the state and wrt the states TrackRep. The state will usually be the prediction or reference state, and has to be defined AT the measurement. The AbsMeasurement will be projected onto the plane. It's possible to make corrections to the coordinates here (e.g. by using the state coordinates). Usually the vector will contain only one element. But in the case of e.g. a WireMeasurement, it will be 2 (left and right).
Implements genfit::AbsMeasurement.
Definition at line 55 of file PlanarMeasurement.cc.
References constructHMatrix(), genfit::StateOnPlane::getPlane(), genfit::StateOnPlane::getRep(), genfit::AbsMeasurement::rawHitCoords_, and genfit::AbsMeasurement::rawHitCov_.
constructPlane()
SharedPlanePtr genfit::PlanarMeasurement::constructPlane (const StateOnPlane & state) const virtual
Construct (virtual) detector plane (use state's AbsTrackRep). It's possible to make corrections to the plane here. The state should be defined somewhere near the measurement. For virtual planes, the state will be extrapolated to the POCA to point (SpacepointMeasurement) or line (WireMeasurement), and from this info the plane will be constructed.
Implements genfit::AbsMeasurement.
Definition at line 46 of file PlanarMeasurement.cc.
References physicalPlane_.
getPlaneId()
int genfit::PlanarMeasurement::getPlaneId () const inline
Definition at line 54 of file PlanarMeasurement.h.
References planeId_.
Referenced by genfit::GFGbl::processTrackWithRep().
setPlane()
virtual void genfit::PlanarMeasurement::setPlane (const SharedPlanePtr & physicalPlane, int planeId = -1) inline virtual
Definition at line 62 of file PlanarMeasurement.h.
References physicalPlane_, and planeId_.
setStripV()
void genfit::PlanarMeasurement::setStripV (bool v = true) inline
Use if the coordinate for 1D hits measured in V direction.
Per default for 1D planar hits, the coordinate is measured in U direction. With this function you can set it to be measured in V direction. This affects the outcoe of constructHMatrix().
Definition at line 70 of file PlanarMeasurement.h.
References stripV_.
Member Data Documentation
physicalPlane_
SharedPlanePtr genfit::PlanarMeasurement::physicalPlane_ protected
Definition at line 73 of file PlanarMeasurement.h.
Referenced by constructPlane(), and setPlane().
planeId_
int genfit::PlanarMeasurement::planeId_ protected
This is persistent, but '!' makes ROOT shut up.
Definition at line 74 of file PlanarMeasurement.h.
Referenced by getPlaneId(), and setPlane().
stripV_
bool genfit::PlanarMeasurement::stripV_ protected
Definition at line 75 of file PlanarMeasurement.h.
Referenced by constructHMatrix(), and setStripV().
The documentation for this class was generated from the following files:
/home/eicuser/GenFit/measurements/include/PlanarMeasurement.h
/home/eicuser/GenFit/measurements/src/PlanarMeasurement.cc