GENFIT: genfit Namespace Reference
genfit Namespace Reference
Genfit | EventDisplay | GFRave | RKTrackRep | Utilities
Defines for I/O streams used for error and debug printing.
Namespaces
Constants
RKTools
Array matrix multiplications used in RKTrackRep.
tools
Unit
Classes
class AbsBField
Abstract Interface to magnetic fields in GENFIT.
class AbsFinitePlane
Abstract base class for finite detector planes.
class AbsFitter
Abstract base class for fitters.
class AbsFitterInfo
This class collects all information needed and produced by a specific AbsFitter and is specific to one AbsTrackRep of the Track.
class AbsHMatrix
HMatrix for projecting from AbsTrackRep parameters to measured parameters in a DetPlane.
class AbsKalmanFitter
Abstract base class for Kalman fitter and derived fitting algorithms.
class AbsMaterialInterface
Abstract base class for geometry interfacing.
class AbsMeasurement
Contains the measurement and covariance in raw detector coordinates.
class AbsMeasurementProducer
Abstract interface class for MeasurementProducer.
class AbsTrackRep
Abstract base class for a track representation.
class ConstField
Constant Magnetic field.
class DAF
Determinstic Annealing Filter (DAF) implementation.
class DetPlane
Detector plane.
class EventDisplay
Event display designed to run with Genfit.
class Exception
Exception class for error handling in GENFIT (provides storage for diagnostic information)
struct ExtrapStep
Helper for RKTrackRep.
struct fieldCache
Cache B field at a position. Used by FieldManager.
class FieldManager
Singleton which provides access to magnetic field maps.
class FitStatus
Class where important numbers and properties of a fit can be stored.
class FullMeasurement
Measurement class implementing a measurement of all track parameters.
class GblFitStatus
FitStatus for use with GblFitter.
class GblFitter
Generic GBL implementation.
class GblFitterInfo
Collects information needed and produced by a GblFitter/GBL and is specific to one AbsTrackRep of the Track.
class GblTrackSegmentController
TrackSegmentController for use with GblFitter.
class GFGbl
Generic GBL implementation.
class GFRaveMagneticField
GFRaveMagneticField class Uses the FieldManager to provide a magnetic field to rave.
class GFRavePropagator
GFRavePropagator class.
class GFRaveTrackParameters
GFRaveTrackParameters class Contains a pointer to the original genfit::Track, the weight of the track in the vertex, and smoothed (with the vertex information) state and covariance of the track.
class GFRaveVertex
GFRaveVertex class.
class GFRaveVertexFactory
Vertex factory for producing GFRaveVertex objects from Track objects.
class HelixTrackModel
Helix track model for testing purposes.
class HMatrixPhi
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixU
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixUnit
AbsHMatrix implementation for 5-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixUV
AbsHMatrix implementation for two-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class HMatrixV
AbsHMatrix implementation for one-dimensional MeasurementOnPlane and RKTrackRep parameterization.
class ICalibrationParametersDerivatives
Abstract base class to establish an interface between physical representation of the detector for alignment/calibration and (fitted) state on genfit::Track.
class KalmanFitStatus
FitStatus for use with AbsKalmanFitter implementations.
class KalmanFittedStateOnPlane
MeasuredStateOnPlane with additional info produced by a Kalman filter or DAF.
class KalmanFitter
Simple Kalman filter implementation.
class KalmanFitterInfo
Collects information needed and produced by a AbsKalmanFitter implementations and is specific to one AbsTrackRep of the Track.
class KalmanFitterRefTrack
Kalman filter implementation with linearization around a reference track.
struct Material
class MaterialEffects
Stepper and energy loss/noise matrix calculation.
struct MatStep
Simple struct containing MaterialProperties and stepsize in the material.
class MeasuredStateOnPlane
StateOnPlane with additional covariance matrix.
class MeasurementCreator
Create different measurement types along a HelixTrackModel for testing purposes.
class MeasurementFactory
Factory object to create AbsMeasurement objects from digitized and clustered data.
class MeasurementOnPlane
Measured coordinates on a plane.
class MeasurementProducer
Template class for a measurement producer module.
class mySpacepointDetectorHit
Example class for a spacepoint detector hit.
class mySpacepointMeasurement
Example class for a spacepoint measurement which can be created from mySpacepointDetectorHit via the MeasurementFactory.
class PlanarMeasurement
Measurement class implementing a planar hit geometry (1 or 2D).
class ProlateSpacepointMeasurement
Class for measurements implementing a space point hit geometry with a very prolate form of the covariance matrix.
struct PruneFlags
Info which information has been pruned from the Track.
class RectangularFinitePlane
Rectangular finite plane.
class ReferenceStateOnPlane
StateOnPlane with linearized transport to that ReferenceStateOnPlane from previous and next ReferenceStateOnPlane
struct RKMatrix
struct RKStep
Helper for RKTrackRep.
class RKTrackRep
AbsTrackRep with 5D track parameterization in plane coordinates: (q/p, u', v', u, v)
class SharedPlanePtrCreator
class SpacepointMeasurement
Class for measurements implementing a space point hit geometry.
class StateOnPlane
A state with arbitrary dimension defined in a DetPlane.
class StepLimits
Helper to store different limits on the stepsize for the RKTRackRep.
class TGeoMaterialInterface
AbsMaterialInterface implementation for use with ROOT's TGeoManager.
class ThinScatterer
Thin or thick scatterer.
class Track
Collection of TrackPoint objects, AbsTrackRep objects and FitStatus objects.
struct trackAndState
Simple struct containing a Track pointer and a MeasuredStateOnPlane. Used in GFRave.
class TrackCand
Track candidate – seed values and indices.
class TrackCandHit
Hit object for use in TrackCand. Provides IDs and sorting parameters.
class TrackPoint
Object containing AbsMeasurement and AbsFitterInfo objects.
class TrackPointComparator
Helper class for TrackPoint sorting, used in Track::sort().
class WireMeasurement
Class for measurements in wire detectors (Straw tubes and drift chambers) which do not measure the coordinate along the wire.
class WireMeasurementNew
Class for measurements in wire detectors (Straw tubes and drift chambers) which do not measure the coordinate along the wire.
class WirePointMeasurement
Class for measurements in wire detectors (Straw tubes and drift chambers) which can measure the coordinate along the wire.
class WireTrackCandHit
Hit object for use in TrackCand. Provides additional left/right parameter.
Typedefs
typedef double Precision
typedef Precision Scalar
typedef Eigen::Matrix< Precision, 3, 1 > Vector3
typedef Eigen::Matrix< Precision, 5, 1 > Vector5
typedef Eigen::Matrix< Precision, 6, 1 > Vector6
typedef Eigen::Matrix< Precision, 7, 1 > Vector7
typedef Eigen::Matrix< Precision, 3, 3 > Matrix3x3
typedef Eigen::Matrix< Precision, 4, 4 > Matrix4x4
typedef Eigen::Matrix< Precision, 5, 5 > Matrix5x5
typedef Eigen::Matrix< Precision, 6, 6 > Matrix6x6
typedef Eigen::Matrix< Precision, 7, 7 > Matrix7x7
typedef Eigen::Matrix< Precision, Eigen::Dynamic, 1 > VectorDynamic
typedef Eigen::Matrix< Precision, Eigen::Dynamic, Eigen::Dynamic > MatrixDynamic
typedef Matrix3x3 Matrix3x3Sym
typedef Matrix4x4 Matrix4x4Sym
typedef Matrix5x5 Matrix5x5Sym
typedef Matrix6x6 Matrix6x6Sym
typedef Matrix7x7 Matrix7x7Sym
typedef std::shared_ptr< genfit::DetPlane > SharedPlanePtr
Shared Pointer to a DetPlane.
typedef RKMatrix< 1, 3 > M1x3
typedef RKMatrix< 1, 4 > M1x4
typedef RKMatrix< 1, 7 > M1x7
typedef RKMatrix< 5, 5 > M5x5
typedef RKMatrix< 6, 6 > M6x6
typedef RKMatrix< 7, 7 > M7x7
typedef RKMatrix< 6, 5 > M6x5
typedef RKMatrix< 7, 5 > M7x5
typedef RKMatrix< 5, 6 > M5x6
typedef RKMatrix< 5, 7 > M5x7
Enumerations
enum eFitterType { SimpleKalman, RefKalman, DafSimple, DafRef }
enum eMultipleMeasurementHandling {
weightedAverage, unweightedAverage, weightedClosestToReference, unweightedClosestToReference,
weightedClosestToPrediction, unweightedClosestToPrediction, weightedClosestToReferenceWire, unweightedClosestToReferenceWire,
weightedClosestToPredictionWire, unweightedClosestToPredictionWire
}
enum StepLimitType {
stp_noLimit = 0, stp_fieldCurv, stp_momLoss, stp_sMax,
stp_sMaxArg, stp_boundary, stp_plane, ENUM_NR_ITEMS
}
enum eMeasurementType {
Pixel = 0, Spacepoint, ProlateSpacepoint, StripU,
StripV, StripUV, Wire, WirePoint,
nMeasurementTypes
}
Functions
bool operator== (const DetPlane &lhs, const DetPlane &rhs)
bool operator!= (const DetPlane &lhs, const DetPlane &rhs)
bool operator== (const Material &lhs, const Material &rhs)
bool operator!= (const Material &lhs, const Material &rhs)
MeasuredStateOnPlane calcAverageState (const MeasuredStateOnPlane &forwardState, const MeasuredStateOnPlane &backwardState)
Calculate weighted average between two MeasuredStateOnPlanes.
bool operator== (const TrackCand &lhs, const TrackCand &rhs)
bool operator== (const TrackCandHit &lhs, const TrackCandHit &rhs)
AbsFitterInfo * new_clone (const AbsFitterInfo &a)
Needed for boost cloneability:
std::vector< rave::Track > GFTracksToTracks (const std::vector< genfit::Track * > &GFTracks, std::vector< genfit::MeasuredStateOnPlane * > *GFStates, std::map< int, genfit::trackAndState > &IdGFTrackStateMap, int startID)
rave::Track GFTrackToTrack (trackAndState trackAndState, int id, std::string tag)
void setData (const rave::Track &orig, MeasuredStateOnPlane *state)
GFRaveVertex * RaveToGFVertex (const rave::Vertex &raveVertex, const std::map< int, genfit::trackAndState > &IdGFTrackStateMap)
void RaveToGFVertices (std::vector< GFRaveVertex *> *GFVertices, const std::vector< rave::Vertex > &raveVertices, const std::map< int, genfit::trackAndState > &IdGFTrackStateMap)
SharedPlanePtr PlaneToGFDetPlane (const ravesurf::Plane &rplane)
TVector3 Point3DToTVector3 (const rave::Point3D &v)
TVector3 Vector3DToTVector3 (const rave::Vector3D &v)
TMatrixDSym Covariance3DToTMatrixDSym (const rave::Covariance3D &ravecov)
TVectorD Vector6DToTVectorD (const rave::Vector6D &ravevec)
TMatrixDSym Covariance6DToTMatrixDSym (const rave::Covariance6D &ravecov)
rave::Point3D TVector3ToPoint3D (const TVector3 &vec)
rave::Covariance3D TMatrixDSymToCovariance3D (const TMatrixDSym &matrix)
double MeanExcEnergy_get (int Z)
double MeanExcEnergy_get (TGeoMaterial *)
double MeanExcEnergy_get (int Z, bool logs=false)
template<unsigned int rows, unsigned int cols>
Eigen::Matrix< double, rows, cols > RKMatrixToEigenMatrix (const RKMatrix< rows, cols > &rkMatrix)
template<unsigned int rows, unsigned int cols>
RKMatrix< rows, cols > eigenMatrixToRKMatrix (const Eigen::Matrix< double, rows, cols > &eigenMatrix)
template<unsigned int dim>
Eigen::Matrix< double, dim, 1 > rootVectorToEigenVector (const TVectorD &rootVector)
template<unsigned int dim>
TVectorD eigenVectorToRootVector (const Eigen::Matrix< double, dim, 1 > &eigenVector)
template<unsigned int dim>
Eigen::Matrix< double, dim, dim > rootMatrixSymToEigenMatrix (const TMatrixDSym &rootMatrix)
template<unsigned int dim>
TMatrixDSym eigenMatrixToRootMatrixSym (const Eigen::Matrix< double, dim, dim > &eigenMatrix)
template<unsigned int rows, unsigned int cols>
Eigen::Matrix< double, rows, cols > rootMatrixToEigenMatrix (const TMatrixD &rootMatrix)
template<unsigned int rows, unsigned int cols>
TMatrixD eigenMatrixToRootMatrix (const Eigen::Matrix< double, rows, cols > &eigenMatrix)
Variables
std::ostream debugOut
std::ostream errorOut
std::ostream printOut
const int MeanExcEnergy_NELEMENTS = 93
const double MeanExcEnergy_vals [MeanExcEnergy_NELEMENTS]
const double MeanExcEnergy_logs [MeanExcEnergy_NELEMENTS]
Detailed Description
Defines for I/O streams used for error and debug printing.
Collection of converter functions.
Namespace for the general broken lines package.
Matrix inversion tools.
Typedef Documentation
M1x3
typedef RKMatrix<1, 3> genfit::M1x3
Definition at line 57 of file RKTools.h.
M1x4
typedef RKMatrix<1, 4> genfit::M1x4
Definition at line 58 of file RKTools.h.
M1x7
typedef RKMatrix<1, 7> genfit::M1x7
Definition at line 59 of file RKTools.h.
M5x5
typedef RKMatrix<5, 5> genfit::M5x5
Definition at line 60 of file RKTools.h.
M5x6
typedef RKMatrix<5, 6> genfit::M5x6
Definition at line 65 of file RKTools.h.
M5x7
typedef RKMatrix<5, 7> genfit::M5x7
Definition at line 66 of file RKTools.h.
M6x5
typedef RKMatrix<6, 5> genfit::M6x5
Definition at line 63 of file RKTools.h.
M6x6
typedef RKMatrix<6, 6> genfit::M6x6
Definition at line 61 of file RKTools.h.
M7x5
typedef RKMatrix<7, 5> genfit::M7x5
Definition at line 64 of file RKTools.h.
M7x7
typedef RKMatrix<7, 7> genfit::M7x7
Definition at line 62 of file RKTools.h.
Matrix3x3
typedef Eigen::Matrix<Precision, 3, 3> genfit::Matrix3x3
Definition at line 15 of file EigenMatrixTypedefs.h.
Matrix3x3Sym
typedef Matrix3x3 genfit::Matrix3x3Sym
Definition at line 24 of file EigenMatrixTypedefs.h.
Matrix4x4
typedef Eigen::Matrix<Precision, 4, 4> genfit::Matrix4x4
Definition at line 16 of file EigenMatrixTypedefs.h.
Matrix4x4Sym
typedef Matrix4x4 genfit::Matrix4x4Sym
Definition at line 25 of file EigenMatrixTypedefs.h.
Matrix5x5
typedef Eigen::Matrix<Precision, 5, 5> genfit::Matrix5x5
Definition at line 17 of file EigenMatrixTypedefs.h.
Matrix5x5Sym
typedef Matrix5x5 genfit::Matrix5x5Sym
Definition at line 26 of file EigenMatrixTypedefs.h.
Matrix6x6
typedef Eigen::Matrix<Precision, 6, 6> genfit::Matrix6x6
Definition at line 18 of file EigenMatrixTypedefs.h.
Matrix6x6Sym
typedef Matrix6x6 genfit::Matrix6x6Sym
Definition at line 27 of file EigenMatrixTypedefs.h.
Matrix7x7
typedef Eigen::Matrix<Precision, 7, 7> genfit::Matrix7x7
Definition at line 19 of file EigenMatrixTypedefs.h.
Matrix7x7Sym
typedef Matrix7x7 genfit::Matrix7x7Sym
Definition at line 28 of file EigenMatrixTypedefs.h.
MatrixDynamic
typedef Eigen::Matrix<Precision, Eigen::Dynamic, Eigen::Dynamic> genfit::MatrixDynamic
Definition at line 22 of file EigenMatrixTypedefs.h.
Precision
typedef double genfit::Precision
Definition at line 6 of file EigenMatrixTypedefs.h.
Scalar
typedef Precision genfit::Scalar
Definition at line 8 of file EigenMatrixTypedefs.h.
SharedPlanePtr
typedef std::shared_ptr< genfit::DetPlane > genfit::SharedPlanePtr
Shared Pointer to a DetPlane.
Ownership can be shared, e.g between multiple StateOnPlane objects. The DetPlane will automatically be deleted, if no owner remains.
Definition at line 40 of file SharedPlanePtr.h.
Vector3
typedef Eigen::Matrix<Precision, 3, 1> genfit::Vector3
Definition at line 10 of file EigenMatrixTypedefs.h.
Vector5
typedef Eigen::Matrix<Precision, 5, 1> genfit::Vector5
Definition at line 11 of file EigenMatrixTypedefs.h.
Vector6
typedef Eigen::Matrix<Precision, 6, 1> genfit::Vector6
Definition at line 12 of file EigenMatrixTypedefs.h.
Vector7
typedef Eigen::Matrix<Precision, 7, 1> genfit::Vector7
Definition at line 13 of file EigenMatrixTypedefs.h.
VectorDynamic
typedef Eigen::Matrix<Precision, Eigen::Dynamic, 1> genfit::VectorDynamic
Definition at line 21 of file EigenMatrixTypedefs.h.
Enumeration Type Documentation
eFitterType
enum genfit::eFitterType
Enumerator
SimpleKalman
RefKalman
DafSimple
DafRef
Definition at line 41 of file EventDisplay.h.
eMeasurementType
enum genfit::eMeasurementType
Enumerator
Pixel
Spacepoint
ProlateSpacepoint
StripU
StripV
StripUV
Wire
WirePoint
nMeasurementTypes
Definition at line 42 of file MeasurementCreator.h.
eMultipleMeasurementHandling
enum genfit::eMultipleMeasurementHandling
Enumerator
weightedAverage
weighted average between measurements; used by DAF
unweightedAverage
average between measurements, all weighted with 1
weightedClosestToReference
closest to reference, weighted with its weight_
unweightedClosestToReference
closest to reference, weighted with 1
weightedClosestToPrediction
closest to prediction, weighted with its weight_
unweightedClosestToPrediction
closest to prediction, weighted with 1
weightedClosestToReferenceWire
if corresponding TrackPoint has one WireMeasurement, select closest to reference, weighted with its weight_. Otherwise use weightedAverage.
unweightedClosestToReferenceWire
if corresponding TrackPoint has one WireMeasurement, select closest to reference, weighted with 1. Otherwise use unweightedAverage.
weightedClosestToPredictionWire
if corresponding TrackPoint has one WireMeasurement, select closest to prediction, weighted with its weight_. Otherwise use weightedAverage.
unweightedClosestToPredictionWire
if corresponding TrackPoint has one WireMeasurement, select closest to prediction, weighted with 1. Otherwise use unweightedAverage. Recommended for KalmanFitter to 'resolve' l/r ambiguities
Definition at line 35 of file AbsKalmanFitter.h.
StepLimitType
enum genfit::StepLimitType
Enumerator
stp_noLimit
stp_fieldCurv
stp_momLoss
stp_sMax
stp_sMaxArg
stp_boundary
stp_plane
ENUM_NR_ITEMS
Definition at line 33 of file StepLimits.h.
Function Documentation
calcAverageState()
MeasuredStateOnPlane genfit::calcAverageState (const MeasuredStateOnPlane & forwardState, const MeasuredStateOnPlane & backwardState)
Calculate weighted average between two MeasuredStateOnPlanes.
Definition at line 76 of file MeasuredStateOnPlane.cc.
References genfit::StateOnPlane::getAuxInfo(), genfit::MeasuredStateOnPlane::getCov(), genfit::StateOnPlane::getPlane(), genfit::StateOnPlane::getRep(), genfit::StateOnPlane::getState(), genfit::tools::invertMatrix(), genfit::tools::QR(), genfit::MeasuredStateOnPlane::setCov(), genfit::StateOnPlane::setState(), and genfit::tools::transposedInvert().
Referenced by genfit::KalmanFitterInfo::getFittedState().
Covariance3DToTMatrixDSym()
TMatrixDSym genfit::Covariance3DToTMatrixDSym (const rave::Covariance3D & ravecov)
Definition at line 243 of file GFRaveConverters.cc.
Referenced by RaveToGFVertex().
Covariance6DToTMatrixDSym()
TMatrixDSym genfit::Covariance6DToTMatrixDSym (const rave::Covariance6D & ravecov)
Definition at line 279 of file GFRaveConverters.cc.
Referenced by RaveToGFVertex(), and setData().
eigenMatrixToRKMatrix()
template<unsigned int rows, unsigned int cols> RKMatrix<rows, cols> genfit::eigenMatrixToRKMatrix (const Eigen::Matrix< double, rows, cols > & eigenMatrix)
Definition at line 23 of file RKMatrixEigenTransformations.h.
eigenMatrixToRootMatrix()
template<unsigned int rows, unsigned int cols> TMatrixD genfit::eigenMatrixToRootMatrix (const Eigen::Matrix< double, rows, cols > & eigenMatrix)
Definition at line 82 of file RootEigenTransformations.h.
eigenMatrixToRootMatrixSym()
template<unsigned int dim> TMatrixDSym genfit::eigenMatrixToRootMatrixSym (const Eigen::Matrix< double, dim, dim > & eigenMatrix)
Definition at line 54 of file RootEigenTransformations.h.
eigenVectorToRootVector()
template<unsigned int dim> TVectorD genfit::eigenVectorToRootVector (const Eigen::Matrix< double, dim, 1 > & eigenVector)
Definition at line 25 of file RootEigenTransformations.h.
GFTracksToTracks()
std::vector< rave::Track > genfit::GFTracksToTracks (const std::vector< genfit::Track *> & GFTracks, std::vector< genfit::MeasuredStateOnPlane *> * GFStates, std::map< int, genfit::trackAndState > & IdGFTrackStateMap, int startID = 0)
Convert a vector of genfit::Tracks to rave::Tracks also builds a map of unique ids to genfit::Tracks; These ids are stored in the rave::tracks. They are counted from startID. The map has to be passed to the GFRavePropagator, so that it can access the trackreps of the genfit::Tracks corresponding to the rave::tracks. If a vector of MeasuredStateOnPlane is provided, they will be used (instead of the tracks fitted states) to calculate the rave::Track parameters. Ownership over MeasuredStateOnPlane will be taken.
Definition at line 36 of file GFRaveConverters.cc.
References GFTrackToTrack().
Referenced by genfit::GFRaveVertexFactory::findVertices().
GFTrackToTrack()
rave::Track genfit::GFTrackToTrack (trackAndState trackAndState, int id, std::string tag)
Definition at line 83 of file GFRaveConverters.cc.
References genfit::FitStatus::getCharge(), genfit::FitStatus::getChi2(), genfit::Track::getFitStatus(), genfit::Track::getFittedState(), genfit::FitStatus::getNdf(), genfit::MeasuredStateOnPlane::getPosMomCov(), genfit::FitStatus::isFitConverged(), and genfit::trackAndState::track_.
Referenced by genfit::GFRavePropagator::closestTo(), GFTracksToTracks(), and genfit::GFRavePropagator::to().
MeanExcEnergy_get() [1/3]
double genfit::MeanExcEnergy_get (int Z)
Referenced by genfit::TGeoMaterialInterface::getMaterialParameters(), and MeanExcEnergy_get().
MeanExcEnergy_get() [2/3]
double genfit::MeanExcEnergy_get (TGeoMaterial * mat)
Definition at line 255 of file TGeoMaterialInterface.cc.
References MeanExcEnergy_get().
MeanExcEnergy_get() [3/3]
double genfit::MeanExcEnergy_get (int Z, bool logs = false)
Definition at line 245 of file TGeoMaterialInterface.cc.
References MeanExcEnergy_logs, MeanExcEnergy_NELEMENTS, and MeanExcEnergy_vals.
new_clone()
AbsFitterInfo* genfit::new_clone (const AbsFitterInfo & a) inline
Needed for boost cloneability:
Definition at line 108 of file AbsFitterInfo.h.
References genfit::AbsFitterInfo::clone().
operator!=() [1/2]
bool genfit::operator!= (const Material & lhs, const Material & rhs)
Definition at line 19 of file Material.cc.
operator!=() [2/2]
bool genfit::operator!= (const DetPlane & lhs, const DetPlane & rhs)
Definition at line 262 of file DetPlane.cc.
operator==() [1/4]
bool genfit::operator== (const Material & lhs, const Material & rhs)
Definition at line 7 of file Material.cc.
References genfit::Material::A, genfit::Material::density, genfit::Material::mEE, genfit::Material::radiationLength, and genfit::Material::Z.
operator==() [2/4]
bool genfit::operator== (const TrackCandHit & lhs, const TrackCandHit & rhs)
Definition at line 46 of file TrackCandHit.cc.
References genfit::TrackCandHit::detId_, genfit::TrackCandHit::hitId_, and genfit::TrackCandHit::planeId_.
operator==() [3/4]
bool genfit::operator== (const TrackCand & lhs, const TrackCand & rhs)
Definition at line 191 of file TrackCand.cc.
References genfit::TrackCand::getHit(), and genfit::TrackCand::getNHits().
operator==() [4/4]
bool genfit::operator== (const DetPlane & lhs, const DetPlane & rhs)
Definition at line 240 of file DetPlane.cc.
References genfit::DetPlane::o_, genfit::DetPlane::u_, and genfit::DetPlane::v_.
PlaneToGFDetPlane()
SharedPlanePtr genfit::PlaneToGFDetPlane (const ravesurf::Plane & rplane)
Definition at line 225 of file GFRaveConverters.cc.
References Point3DToTVector3(), and Vector3DToTVector3().
Referenced by genfit::GFRavePropagator::to().
Point3DToTVector3()
TVector3 genfit::Point3DToTVector3 (const rave::Point3D & v)
Definition at line 232 of file GFRaveConverters.cc.
Referenced by genfit::GFRavePropagator::closestTo(), PlaneToGFDetPlane(), and RaveToGFVertex().
RaveToGFVertex()
GFRaveVertex * genfit::RaveToGFVertex (const rave::Vertex & raveVertex, const std::map< int, genfit::trackAndState > & IdGFTrackStateMap)
Definition at line 141 of file GFRaveConverters.cc.
References Covariance3DToTMatrixDSym(), Covariance6DToTMatrixDSym(), Point3DToTVector3(), and Vector6DToTVectorD().
Referenced by RaveToGFVertices().
RaveToGFVertices()
void genfit::RaveToGFVertices (std::vector< GFRaveVertex *> * GFVertices, const std::vector< rave::Vertex > & raveVertices, const std::map< int, genfit::trackAndState > & IdGFTrackStateMap)
Definition at line 210 of file GFRaveConverters.cc.
References RaveToGFVertex().
Referenced by genfit::GFRaveVertexFactory::findVertices().
RKMatrixToEigenMatrix()
template<unsigned int rows, unsigned int cols> Eigen::Matrix<double, rows, cols> genfit::RKMatrixToEigenMatrix (const RKMatrix< rows, cols > & rkMatrix)
Definition at line 9 of file RKMatrixEigenTransformations.h.
rootMatrixSymToEigenMatrix()
template<unsigned int dim> Eigen::Matrix<double, dim, dim> genfit::rootMatrixSymToEigenMatrix (const TMatrixDSym & rootMatrix)
Definition at line 39 of file RootEigenTransformations.h.
rootMatrixToEigenMatrix()
template<unsigned int rows, unsigned int cols> Eigen::Matrix<double, rows, cols> genfit::rootMatrixToEigenMatrix (const TMatrixD & rootMatrix)
Definition at line 67 of file RootEigenTransformations.h.
rootVectorToEigenVector()
template<unsigned int dim> Eigen::Matrix<double, dim, 1> genfit::rootVectorToEigenVector (const TVectorD & rootVector)
Definition at line 10 of file RootEigenTransformations.h.
setData()
void genfit::setData (const rave::Track & orig, MeasuredStateOnPlane * state)
set state and cov of a MeasuredStateOnPlane according to rave track
Definition at line 131 of file GFRaveConverters.cc.
References Covariance6DToTMatrixDSym(), and genfit::MeasuredStateOnPlane::setPosMomCov().
TMatrixDSymToCovariance3D()
rave::Covariance3D genfit::TMatrixDSymToCovariance3D (const TMatrixDSym & matrix)
Definition at line 335 of file GFRaveConverters.cc.
Referenced by genfit::GFRaveVertexFactory::setBeamspot().
TVector3ToPoint3D()
rave::Point3D genfit::TVector3ToPoint3D (const TVector3 & vec)
Definition at line 329 of file GFRaveConverters.cc.
Referenced by genfit::GFRaveVertexFactory::setBeamspot().
Vector3DToTVector3()
TVector3 genfit::Vector3DToTVector3 (const rave::Vector3D & v)
Definition at line 237 of file GFRaveConverters.cc.
Referenced by PlaneToGFDetPlane().
Vector6DToTVectorD()
TVectorD genfit::Vector6DToTVectorD (const rave::Vector6D & ravevec)
Definition at line 263 of file GFRaveConverters.cc.
Referenced by RaveToGFVertex().
Variable Documentation
debugOut
std::ostream genfit::debugOut
Default stream for debug output. Defaults to std::cout. Override destination with debugOut.rdbuf(newStream.rdbuf()).
Referenced by genfit::RKTrackRep::calcForwardJacobianAndNoise(), genfit::DAF::calcWeights(), genfit::RKTrackRep::checkCache(), genfit::Track::deleteBackwardInfo(), genfit::Track::deleteFitterInfo(), genfit::Track::deleteForwardInfo(), genfit::Track::deleteMeasurementInfo(), genfit::Track::deletePoint(), genfit::Track::deleteReferenceInfo(), genfit::MaterialEffects::effects(), genfit::RKTrackRep::estimateStep(), genfit::RKTrackRep::Extrap(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), genfit::TGeoMaterialInterface::findNextBoundary(), genfit::KalmanFitterRefTrack::fitTrack(), genfit::KalmanFitter::fitTrack(), genfit::RKTrackRep::getBackwardJacobianAndNoise(), genfit::KalmanFitterInfo::getFittedState(), genfit::RKTrackRep::getForwardJacobianAndNoise(), genfit::Exception::info(), genfit::TGeoMaterialInterface::initTrack(), genfit::Track::insertPoint(), genfit::Track::mergeTrack(), genfit::MaterialEffects::momentumLoss(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), genfit::Track::prune(), genfit::KalmanFitterRefTrack::removeOutdated(), genfit::RKTrackRep::RKPropagate(), genfit::RKTrackRep::RKutta(), genfit::Track::sort(), genfit::MaterialEffects::stepper(), and genfit::Track::trackHasChanged().
errorOut
std::ostream genfit::errorOut
Default stream for error output. Defaults to std::cerr. Override destination with errorOut.rdbuf(newStream.rdbuf()).
Referenced by genfit::DAF::calcWeights(), genfit::KalmanFitterInfo::checkConsistency(), genfit::FieldManager::checkInitialized(), genfit::FieldManager::checkInstanciated(), genfit::KalmanFitter::fitTrack(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), genfit::DAF::processTrackWithRep(), genfit::ReferenceStateOnPlane::ReferenceStateOnPlane(), genfit::Track::setCardinalRep(), genfit::MaterialEffects::setMscModel(), and genfit::KalmanFitterInfo::setWeights().
MeanExcEnergy_logs
const double genfit::MeanExcEnergy_logs[MeanExcEnergy_NELEMENTS]
Initial value:
= {
  34.5388, 2.95491, 3.7329, 3.68888, 4.15418, 4.33073, 4.35671, 4.40672,
  4.55388, 4.74493, 4.91998, 5.00395, 5.04986, 5.11199, 5.15329, 5.15329,
  5.19296, 5.15906, 5.23644, 5.24702, 5.25227, 5.37528, 5.45104, 5.50126,
  5.54908, 5.6058, 5.65599, 5.69373, 5.73979, 5.77455, 5.79909, 5.81114,
  5.85793, 5.84932, 5.8522, 5.83773, 5.86363, 5.8944, 5.90263, 5.93754,
  5.97381, 6.03309, 6.04973, 6.05912, 6.08904, 6.10702, 6.15273, 6.15273,
  6.1506, 6.19032, 6.19032, 6.18826, 6.18415, 6.19644, 6.17794, 6.19032,
  6.19644, 6.21661, 6.25958, 6.28227, 6.30262, 6.32794, 6.35263, 6.36303,
  6.38182, 6.41999, 6.44254, 6.47697, 6.4892, 6.51323, 6.52796, 6.54247,
  6.5582, 6.57647, 6.58893, 6.60123, 6.61473, 6.62936, 6.67203, 6.67203,
  6.68461, 6.69703, 6.71296, 6.71296, 6.72143, 6.71538, 6.67708, 6.7178,
  6.71659, 6.73459, 6.7417, 6.77765, 6.79122, }
Definition at line 229 of file TGeoMaterialInterface.cc.
Referenced by MeanExcEnergy_get().
MeanExcEnergy_NELEMENTS
const int genfit::MeanExcEnergy_NELEMENTS = 93
Definition at line 214 of file TGeoMaterialInterface.cc.
Referenced by MeanExcEnergy_get().
MeanExcEnergy_vals
const double genfit::MeanExcEnergy_vals[MeanExcEnergy_NELEMENTS]
Initial value:
= {
  1.e15, 19.2, 41.8, 40.0, 63.7, 76.0, 78., 82.0,
  95.0, 115.0, 137.0, 149.0, 156.0, 166.0, 173.0, 173.0,
  180.0, 174.0, 188.0, 190.0, 191.0, 216.0, 233.0, 245.0,
  257.0, 272.0, 286.0, 297.0, 311.0, 322.0, 330.0, 334.0,
  350.0, 347.0, 348.0, 343.0, 352.0, 363.0, 366.0, 379.0,
  393.0, 417.0, 424.0, 428.0, 441.0, 449.0, 470.0, 470.0,
  469.0, 488.0, 488.0, 487.0, 485.0, 491.0, 482.0, 488.0,
  491.0, 501.0, 523.0, 535.0, 546.0, 560.0, 574.0, 580.0,
  591.0, 614.0, 628.0, 650.0, 658.0, 674.0, 684.0, 694.0,
  705.0, 718.0, 727.0, 736.0, 746.0, 757.0, 790.0, 790.0,
  800.0, 810.0, 823.0, 823.0, 830.0, 825.0, 794.0, 827.0,
  826.0, 841.0, 847.0, 878.0, 890.0, }
Definition at line 215 of file TGeoMaterialInterface.cc.
Referenced by MeanExcEnergy_get().
printOut
std::ostream genfit::printOut
Default stream for output of Print calls. Defaults to std::cout. Override destination with printOut.rdbuf(newStream.rdbuf()).
Referenced by genfit::Material::Print(), genfit::RectangularFinitePlane::Print(), genfit::ThinScatterer::Print(), genfit::HMatrixPhi::Print(), genfit::HMatrixU::Print(), genfit::HMatrixV::Print(), genfit::TrackCandHit::Print(), genfit::PruneFlags::Print(), genfit::HMatrixUnit::Print(), genfit::HMatrixUV::Print(), genfit::WireTrackCandHit::Print(), genfit::KalmanFitStatus::Print(), genfit::MeasurementOnPlane::Print(), genfit::MeasuredStateOnPlane::Print(), genfit::ReferenceStateOnPlane::Print(), genfit::StepLimits::Print(), genfit::AbsMeasurement::Print(), genfit::KalmanFitterInfo::Print(), genfit::TrackPoint::Print(), genfit::DetPlane::Print(), genfit::StateOnPlane::Print(), genfit::FitStatus::Print(), genfit::TrackCand::Print(), genfit::Track::Print(), genfit::AbsTrackRep::Print(), and genfit::RKTools::printDim().